[package]
name = "rust-notification-timer"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4.5.10"
tokio = { version = "1.21.2", features = ["full"] }
